### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by purcell**
I saw a few small things that warranted tidying up, but just be warned that I've not tested this extensively. Let's see what the CI says.

### CODE REVIEW

**Comment by joachimschmidt557** [comment]
Apart from the green CI, the changes also look good to me when testing locally. Thanks a lot!

**Comment by purcell** [comment]
Great, thanks.

**Comment by joachimschmidt557** [comment]
> I stopped short of converting the regexps to `rx`, which would be a nice tidy-up, but requires a bit more testing.

I tried that ~2 years ago when we still supported older Emacsen with reduced `rx` support and quickly gave up. This might be more viable nowadays as we have dropped support for some older versions.

**Comment by joachimschmidt557** [comment]
Ah, found what I was talking about: https://github.com/ziglang/zig-mode/pull/45

I didn't "give up", it got merged but broke the CI because of limited support for older versions.

**Comment by purcell** [comment]
Ah nice. I might take a fresh look if I feel in the mood for more random tinkering.

**Pull request merged**
